# Generated by Django 3.0.5 on 2020-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('phone_no', models.BigIntegerField(default=None, verbose_name='phone_no')),
                ('state_code', models.IntegerField(verbose_name='state_code')),
                ('GST_NO', models.CharField(max_length=20, unique=True, verbose_name='GST_NO')),
            ],
        ),
    ]
