# Generated by Django 3.0.5 on 2020-07-30 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, unique=True, verbose_name='invoice_no')),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2020, 7, 30, 23, 26, 53, 437535), verbose_name='invoice_date')),
                ('challanno', models.CharField(default=None, max_length=20, verbose_name='challan_no')),
                ('challan_date', models.DateTimeField(default=None, verbose_name='challan_date')),
                ('PO_no', models.IntegerField(default=None, verbose_name='PO_no')),
                ('Transport', models.CharField(default=None, max_length=100, verbose_name='Transport')),
                ('LR_no', models.IntegerField(default=None, verbose_name='LR_no')),
                ('LR_date', models.DateTimeField(default=None, verbose_name='LR_date')),
                ('no', models.IntegerField(default=None, verbose_name='no')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('Hsncode', models.IntegerField(default=None, verbose_name='Hsncode')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('qty_total', models.IntegerField(verbose_name='total')),
                ('subtotal', models.FloatField(max_length=50, verbose_name='subtotal')),
                ('CGST', models.FloatField(max_length=40, verbose_name='CGST')),
                ('SGST', models.FloatField(max_length=40, verbose_name='SGST')),
                ('IGST', models.FloatField(max_length=40, verbose_name='IGST')),
                ('Round_OFF', models.FloatField(max_length=40, verbose_name='Round_OFF')),
                ('final_total', models.FloatField(max_length=50, verbose_name='final_total')),
                ('GST_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partieGST_NO', to='billing.partie')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partie_address', to='billing.partie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partie_name', to='billing.partie')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_state_code', to='billing.partie')),
            ],
        ),
    ]
